{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-20 14:23:35.417250: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory\n",
      "2023-02-20 14:23:35.417384: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory\n",
      "2023-02-20 14:23:35.417394: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n"
     ]
    }
   ],
   "source": [
    "from circuit import gen_random_circuits\n",
    "from upstream import RandomwalkModel\n",
    "from collections import defaultdict\n",
    "\n",
    "import math\n",
    "from utils.backend import gen_grid_topology, get_grid_neighbor_info, Backend\n",
    "# from utils.backend import default_basis_single_gates, default_basis_two_gates\n",
    "\n",
    "\n",
    "import pennylane as qml\n",
    "import numpy as np\n",
    "from downstream.synthesis.pennylane_op import layer_circuit_to_pennylane_circuit, layer_circuit_to_pennylane_tape\n",
    "from downstream.synthesis.tensor_network_op import layer_circuit_to_matrix\n",
    "from downstream.synthesis import matrix_distance_squared\n",
    "from sklearn.utils import shuffle\n",
    "\n",
    "import cloudpickle as pickle\n",
    "from utils.backend import gen_grid_topology, get_grid_neighbor_info, Backend\n",
    "from circuit import gen_random_circuits\n",
    "from upstream import RandomwalkModel\n",
    "# from downstream.synthesis.pennylane_op import layer_circuit_to_pennylane_circuit, layer_circuit_to_pennylane_tape\n",
    "from downstream.synthesis.tensor_network_op import layer_circuit_to_matrix\n",
    "# from downstream.synthesis.neural_network import NeuralNetworkModel\n",
    "from sklearn.neural_network import MLPRegressor as DNN\n",
    "\n",
    "from jax import numpy as jnp\n",
    "from jax import vmap\n",
    "import jax\n",
    "import optax\n",
    "from jax.config import config\n",
    "import pennylane as qml\n",
    "from pennylane import numpy as pnp\n",
    "import numpy as np\n",
    "from scipy.stats import unitary_group\n",
    "import random\n",
    "import copy\n",
    "import ray\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "# ray.init()\n",
    "\n",
    "\n",
    "grid_num = 2\n",
    "topology = gen_grid_topology(grid_num) # 3x3 9 qubits\n",
    "neigh_info = get_grid_neighbor_info(grid_num, 1)\n",
    "\n",
    "\n",
    "n_qubits = grid_num ** 2\n",
    "backend = Backend(n_qubits=n_qubits, topology=topology, neighbor_info=neigh_info, basis_single_gates = ['u'], \n",
    "                  basis_two_gates = ['cz'], divide = False, decoupling=False)\n",
    "\n",
    "\n",
    "\n",
    "from downstream.synthesis import SynthesisModel\n",
    "from scipy.stats import unitary_group\n",
    "# import warnings\n",
    "# warnings.filterwarnings(\"ignore\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "def transformU(U):\n",
    "    '''转成神经网络里面的格式'''\n",
    "    U = U.reshape(U.size)\n",
    "    U = jnp.concatenate([U.imag, U.real])\n",
    "    U = jnp.array(U, dtype = jnp.float64)\n",
    "    return U"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "finish random circuit generation with 3600 circuits\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705441)\u001b[0m train:0/360, 0th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2708976)\u001b[0m train:0/360, 720th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705441)\u001b[0m train:100/360, 0th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705435)\u001b[0m train:0/360, 360th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705441)\u001b[0m train:200/360, 0th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705418)\u001b[0m train:0/360, 1080th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2708976)\u001b[0m train:100/360, 720th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705440)\u001b[0m train:0/360, 1440th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705441)\u001b[0m train:300/360, 0th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705435)\u001b[0m train:100/360, 360th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705437)\u001b[0m train:0/360, 2160th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705423)\u001b[0m train:0/360, 1800th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705435)\u001b[0m train:200/360, 360th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705418)\u001b[0m train:100/360, 1080th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705460)\u001b[0m train:0/360, 2880th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2708976)\u001b[0m train:200/360, 720th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705435)\u001b[0m train:300/360, 360th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705444)\u001b[0m train:0/360, 3240th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705440)\u001b[0m train:100/360, 1440th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2709041)\u001b[0m train:0/360, 2520th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2708976)\u001b[0m train:300/360, 720th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705418)\u001b[0m train:200/360, 1080th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705437)\u001b[0m train:100/360, 2160th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705423)\u001b[0m train:100/360, 1800th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705440)\u001b[0m train:200/360, 1440th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705418)\u001b[0m train:300/360, 1080th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705460)\u001b[0m train:100/360, 2880th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2709041)\u001b[0m train:100/360, 2520th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705437)\u001b[0m train:200/360, 2160th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705444)\u001b[0m train:100/360, 3240th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705423)\u001b[0m train:200/360, 1800th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705440)\u001b[0m train:300/360, 1440th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2709041)\u001b[0m train:200/360, 2520th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705460)\u001b[0m train:200/360, 2880th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705423)\u001b[0m train:300/360, 1800th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705437)\u001b[0m train:300/360, 2160th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705444)\u001b[0m train:200/360, 3240th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705460)\u001b[0m train:300/360, 2880th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2709041)\u001b[0m train:300/360, 2520th offest\n",
      "\u001b[2m\u001b[36m(remote_train pid=2705444)\u001b[0m train:300/360, 3240th offest\n",
      "random walk finish device size =  8\n",
      "0 path table size =  11\n",
      "1 path table size =  10\n",
      "2 path table size =  11\n",
      "3 path table size =  11\n",
      "(2, 3) path table size =  11\n",
      "(0, 2) path table size =  11\n",
      "(1, 3) path table size =  11\n",
      "(0, 1) path table size =  11\n",
      "start gen Us -> gate_vectos\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(_gen_data pid=2705460)\u001b[0m 2023-02-20 11:08:10.914277: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705460)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705440)\u001b[0m 2023-02-20 11:08:11.104525: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705440)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709041)\u001b[0m 2023-02-20 11:08:11.094414: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709041)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705444)\u001b[0m 2023-02-20 11:08:11.295054: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705444)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708976)\u001b[0m 2023-02-20 11:08:11.256548: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708976)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705435)\u001b[0m 2023-02-20 11:08:11.317348: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705435)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705441)\u001b[0m 2023-02-20 11:08:11.390398: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705441)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705423)\u001b[0m 2023-02-20 11:08:11.364656: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705423)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705437)\u001b[0m 2023-02-20 11:08:11.375968: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705437)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705418)\u001b[0m 2023-02-20 11:08:11.390378: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705418)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705455)\u001b[0m 2023-02-20 11:08:11.982060: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705455)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708895)\u001b[0m 2023-02-20 11:08:12.207191: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708895)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707188)\u001b[0m 2023-02-20 11:08:12.482148: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707188)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705442)\u001b[0m 2023-02-20 11:08:12.949744: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705442)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2706153)\u001b[0m 2023-02-20 11:08:13.640630: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2706153)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708698)\u001b[0m 2023-02-20 11:08:14.308972: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708698)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710310)\u001b[0m 2023-02-20 11:08:14.749418: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710310)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705421)\u001b[0m 2023-02-20 11:08:15.378390: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705421)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705436)\u001b[0m 2023-02-20 11:08:15.500338: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705436)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710052)\u001b[0m 2023-02-20 11:08:15.718009: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710052)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705403)\u001b[0m 2023-02-20 11:08:15.897157: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705403)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708977)\u001b[0m 2023-02-20 11:08:16.118759: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708977)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707141)\u001b[0m 2023-02-20 11:08:16.150436: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707141)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709246)\u001b[0m 2023-02-20 11:08:16.288912: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709246)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705445)\u001b[0m 2023-02-20 11:08:16.491522: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705445)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707672)\u001b[0m 2023-02-20 11:08:16.600535: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707672)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705419)\u001b[0m 2023-02-20 11:08:16.756790: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705419)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705420)\u001b[0m 2023-02-20 11:08:17.317993: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705420)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709840)\u001b[0m 2023-02-20 11:08:17.361693: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709840)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705508)\u001b[0m 2023-02-20 11:08:17.413187: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705508)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2706203)\u001b[0m 2023-02-20 11:08:17.723390: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2706203)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710465)\u001b[0m 2023-02-20 11:08:17.739881: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710465)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709448)\u001b[0m 2023-02-20 11:08:17.776629: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709448)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705653)\u001b[0m 2023-02-20 11:08:17.789443: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705653)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709055)\u001b[0m 2023-02-20 11:08:17.967332: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709055)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705882)\u001b[0m 2023-02-20 11:08:18.166471: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705882)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710453)\u001b[0m 2023-02-20 11:08:18.210240: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710453)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710305)\u001b[0m 2023-02-20 11:08:18.227307: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710305)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705972)\u001b[0m 2023-02-20 11:08:18.473711: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705972)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709318)\u001b[0m 2023-02-20 11:08:18.608352: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709318)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710472)\u001b[0m 2023-02-20 11:08:18.619826: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710472)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708975)\u001b[0m 2023-02-20 11:08:18.728286: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708975)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709841)\u001b[0m 2023-02-20 11:08:18.748282: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709841)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709382)\u001b[0m 2023-02-20 11:08:18.829475: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709382)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709449)\u001b[0m 2023-02-20 11:08:19.001403: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709449)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709842)\u001b[0m 2023-02-20 11:08:18.933928: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709842)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705349)\u001b[0m 2023-02-20 11:08:18.949434: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705349)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705350)\u001b[0m 2023-02-20 11:08:18.949449: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705350)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710454)\u001b[0m 2023-02-20 11:08:19.063459: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710454)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708513)\u001b[0m 2023-02-20 11:08:19.078017: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708513)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710473)\u001b[0m 2023-02-20 11:08:19.220666: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710473)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710311)\u001b[0m 2023-02-20 11:08:19.363186: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710311)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705428)\u001b[0m 2023-02-20 11:08:19.446867: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705428)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705433)\u001b[0m 2023-02-20 11:08:19.377382: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705433)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705429)\u001b[0m 2023-02-20 11:08:19.544700: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705429)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710309)\u001b[0m 2023-02-20 11:08:19.474698: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710309)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709580)\u001b[0m 2023-02-20 11:08:19.522701: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709580)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708087)\u001b[0m 2023-02-20 11:08:19.629863: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708087)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705450)\u001b[0m 2023-02-20 11:08:19.658575: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705450)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705361)\u001b[0m 2023-02-20 11:08:19.717355: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705361)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709042)\u001b[0m 2023-02-20 11:08:19.733964: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709042)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "finished rate = 0 / 3600\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(_gen_data pid=2709844)\u001b[0m 2023-02-20 11:08:19.827462: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709844)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708176)\u001b[0m 2023-02-20 11:08:19.844974: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708176)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709488)\u001b[0m 2023-02-20 11:08:19.864797: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709488)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707513)\u001b[0m 2023-02-20 11:08:20.028447: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707513)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705422)\u001b[0m 2023-02-20 11:08:20.005807: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705422)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710471)\u001b[0m 2023-02-20 11:08:19.989998: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710471)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710307)\u001b[0m 2023-02-20 11:08:19.965116: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710307)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705426)\u001b[0m 2023-02-20 11:08:20.139253: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705426)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709925)\u001b[0m 2023-02-20 11:08:20.049697: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709925)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705971)\u001b[0m 2023-02-20 11:08:20.104428: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705971)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705446)\u001b[0m 2023-02-20 11:08:20.071134: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705446)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705453)\u001b[0m 2023-02-20 11:08:20.262709: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705453)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709056)\u001b[0m 2023-02-20 11:08:20.223141: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709056)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705434)\u001b[0m 2023-02-20 11:08:20.190572: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705434)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705432)\u001b[0m 2023-02-20 11:08:20.187440: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705432)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705457)\u001b[0m 2023-02-20 11:08:20.244021: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705457)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705443)\u001b[0m 2023-02-20 11:08:20.174167: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705443)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705348)\u001b[0m 2023-02-20 11:08:20.316379: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705348)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705454)\u001b[0m 2023-02-20 11:08:20.339119: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705454)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705699)\u001b[0m 2023-02-20 11:08:20.291098: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705699)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710436)\u001b[0m 2023-02-20 11:08:20.369791: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710436)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710455)\u001b[0m 2023-02-20 11:08:20.291104: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710455)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709450)\u001b[0m 2023-02-20 11:08:20.352989: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709450)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707072)\u001b[0m 2023-02-20 11:08:20.405449: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707072)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705427)\u001b[0m 2023-02-20 11:08:20.459548: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705427)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707367)\u001b[0m 2023-02-20 11:08:20.482707: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707367)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705451)\u001b[0m 2023-02-20 11:08:20.405446: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705451)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708103)\u001b[0m 2023-02-20 11:08:20.493285: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2708103)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705568)\u001b[0m 2023-02-20 11:08:20.430976: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705568)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705461)\u001b[0m 2023-02-20 11:08:20.475960: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705461)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705352)\u001b[0m 2023-02-20 11:08:20.527870: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705352)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705351)\u001b[0m 2023-02-20 11:08:20.510942: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705351)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709383)\u001b[0m 2023-02-20 11:08:20.505374: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709383)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710053)\u001b[0m 2023-02-20 11:08:20.514248: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710053)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705459)\u001b[0m 2023-02-20 11:08:20.579161: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705459)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705431)\u001b[0m 2023-02-20 11:08:20.586888: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705431)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705425)\u001b[0m 2023-02-20 11:08:20.607778: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705425)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705447)\u001b[0m 2023-02-20 11:08:20.606515: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705447)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710129)\u001b[0m 2023-02-20 11:08:20.600310: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2710129)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709813)\u001b[0m 2023-02-20 11:08:20.563544: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709813)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707754)\u001b[0m 2023-02-20 11:08:20.595872: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707754)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705448)\u001b[0m 2023-02-20 11:08:20.618818: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705448)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705438)\u001b[0m 2023-02-20 11:08:20.614750: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705438)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705458)\u001b[0m 2023-02-20 11:08:20.616482: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705458)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709455)\u001b[0m 2023-02-20 11:08:20.619586: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2709455)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705456)\u001b[0m 2023-02-20 11:08:20.623352: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707966)\u001b[0m 2023-02-20 11:08:20.626623: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2707966)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705452)\u001b[0m 2023-02-20 11:08:20.627345: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705452)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705456)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705430)\u001b[0m 2023-02-20 11:08:20.636405: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705430)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705439)\u001b[0m 2023-02-20 11:08:20.659411: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705439)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705424)\u001b[0m 2023-02-20 11:08:20.661471: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
      "\u001b[2m\u001b[36m(_gen_data pid=2705424)\u001b[0m WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "finished rate = 1000 / 3600\n",
      "finished rate = 2000 / 3600\n",
      "finished rate = 3000 / 3600\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "(2543000, 2543000)"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "max_gate = 1000 #4**n_qubits\n",
    "'''生成用于测试的模板电路'''\n",
    "circuits = gen_random_circuits(min_gate = 100, max_gate = max_gate, gate_num_step = max_gate//50, n_circuits = 20, two_qubit_gate_probs=[4, 8], backend = backend, reverse = False, optimize = True, multi_process = True)\n",
    "\n",
    "upstream_model = RandomwalkModel(1, 20, backend = backend, travel_directions=('parallel', 'next'))\n",
    "upstream_model.train(circuits, multi_process = True)\n",
    "\n",
    "def random_params(layer2gates):\n",
    "    layer2gates = copy.deepcopy(layer2gates)\n",
    "    for layer in layer2gates:\n",
    "        for gate in layer:\n",
    "            gate['params'] = [\n",
    "                random.random() * 2 * jnp.pi\n",
    "                for param in gate['params']\n",
    "            ]\n",
    "    return layer2gates\n",
    "\n",
    "@ray.remote\n",
    "def _gen_data(circuit_info, index, n_qubits): \n",
    "    gate_vecs, Us = [], []\n",
    "    layer2gates = circuit_info['layer2gates']\n",
    "    # print(layer2gates)\n",
    "    for layer_index, layer_gates in enumerate(layer2gates):\n",
    "        layer_gates = [\n",
    "            gate\n",
    "            for gate in layer_gates\n",
    "            if len(gate['qubits']) == 1\n",
    "        ]\n",
    "        if len(layer_gates) == 0:\n",
    "            continue\n",
    "        for _ in range(10):\n",
    "            target_gate_index = random.randint(0, len(layer_gates)-1)\n",
    "            target_gate_index = layer_gates[target_gate_index]['id']\n",
    "            target_gate = circuit_info['gates'][target_gate_index]\n",
    "\n",
    "            gate_vec = circuit_info['vecs'][target_gate_index]\n",
    "        \n",
    "            _layer2gates = random_params(layer2gates[layer_index:])\n",
    "            # TODO: 应该有些可以重复利用才对\n",
    "            U = layer_circuit_to_matrix(_layer2gates, n_qubits)  #TODO: vmap\n",
    "            U = transformU(U)\n",
    "            \n",
    "            # 似乎根本没有出现过\n",
    "            # _dists = vmap(matrix_distance_squared, in_axes=(None, 0))(U, jnp.array(U, dtype=jnp.complex128))\n",
    "            # if jnp.any(_dists < 0.1):\n",
    "            #     continuez\n",
    "            \n",
    "            Us.append(U)\n",
    "            gate_vecs.append(np.concatenate([jnp.array(target_gate['qubits']), gate_vec], axis=0)  )\n",
    "            \n",
    "    return gate_vecs, Us\n",
    "\n",
    "print('start gen Us -> gate_vectos')\n",
    "futures = []\n",
    "for index, circuit_info in enumerate(circuits):\n",
    "    # upstream_model.vectorize(circuit_info)\n",
    "    future = _gen_data.remote(circuit_info, index, n_qubits)\n",
    "    # future = _gen_data(circuit_info, n_qubits)\n",
    "    futures.append(future)\n",
    "    \n",
    "gate_vecs, Us = [], []\n",
    "for index, future in enumerate(futures):\n",
    "    if index % 1000 == 0:\n",
    "        print('finished rate =', index, '/', len(futures))\n",
    "    if not isinstance(future, tuple):\n",
    "        future = ray.get(future)\n",
    "    gate_vecs += future[0]\n",
    "    Us += future[1]\n",
    "\n",
    "gate_vecs = jnp.array(gate_vecs, dtype=jnp.float64)\n",
    "Us = jnp.array(Us, dtype=jnp.float64)\n",
    "# Us, Us_test, gate_vecs, gate_vecs_test = train_test_split(Us, gate_vecs, test_size=.1)\n",
    "\n",
    "len(Us), len(gate_vecs), #len(Us_test), len(gate_vecs_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "model_path = 'synthesis_model_1.pkl'\n",
    "# with open(f'./temp_data/{model_path}', 'wb') as file:\n",
    "#     pickle.dump((upstream_model, Us, gate_vecs), file)\n",
    "    \n",
    "with open(f'./temp_data/{model_path}', 'rb') as file:\n",
    "    upstream_model, Us, gate_vecs = pickle.load(file)\n",
    "    \n",
    "upstream_model: RandomwalkModel = upstream_model\n",
    "Us: jnp.array = Us\n",
    "gate_vecs: jnp.array = gate_vecs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(2543000, 2543000)"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(Us), len(gate_vecs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Iteration 1, loss = 0.08012055\n",
      "Iteration 2, loss = 0.07845559\n",
      "Iteration 3, loss = 0.07856213\n",
      "Iteration 4, loss = 0.07865916\n",
      "Iteration 5, loss = 0.07874819\n",
      "Iteration 6, loss = 0.07882974\n",
      "Iteration 7, loss = 0.07892536\n",
      "Iteration 8, loss = 0.07900493\n",
      "Iteration 9, loss = 0.07911803\n",
      "Iteration 10, loss = 0.07923878\n",
      "Iteration 11, loss = 0.07935648\n",
      "Iteration 12, loss = 0.07949335\n",
      "Iteration 13, loss = 0.07962894\n",
      "Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.\n"
     ]
    }
   ],
   "source": [
    "neural_model = DNN((4**n_qubits, upstream_model.max_table_size**2, 2**n_qubits, 2**n_qubits, upstream_model.max_table_size*2), verbose = True, n_iter_no_change=10) #, activation='sigmoid'\n",
    "neural_model.fit(Us, gate_vecs)\n",
    "# neural_model.score(transform(Us_test), gate_vecs_test)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "model_path = 'neural_model_1.pkl'\n",
    "with open(f'./temp_data/{model_path}', 'wb') as file:\n",
    "    pickle.dump(neural_model, file)\n",
    "    \n",
    "with open(f'./temp_data/{model_path}', 'rb') as file:\n",
    "    neural_model = pickle.load(file)\n",
    "    \n",
    "neural_model: DNN = neural_model "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "9"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "upstream_model.max_table_size"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def step_function(x):\n",
    "    return jnp.where(x>0, 1.0, 0.0)\n",
    "\n",
    "def sigmoid(x):\n",
    "    return 1 / (1 + jnp.exp(-x))\n",
    "\n",
    "def final_mapping(mapping, x):\n",
    "    # print(mapping)\n",
    "    return sigmoid(mapping['W'] * x + mapping['B'])\n",
    "\n",
    "def final_mapping_cost(mapping, x, y):\n",
    "    predictions = final_mapping(mapping, x)\n",
    "    return optax.l2_loss(predictions, y).sum()\n",
    "\n",
    "def final_mapping_cost_batch(mapping, X, Y):\n",
    "    return vmap(final_mapping_cost, in_axes=(None, 0, 0))(mapping, X, Y).sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(20000, 11) (20000, 11)\n",
      "epoch  0\t| train loss = 16374.79868\t|  test loss = 3383.22694\n"
     ]
    }
   ],
   "source": [
    "X = neural_model.predict(Us[:20000])[:,1:upstream_model.max_table_size+1]\n",
    "Y = gate_vecs[:,1:upstream_model.max_table_size+1][:20000]\n",
    "print(X.shape, Y.shape)\n",
    "\n",
    "mapping  = {\n",
    "    'W': jax.random.normal(shape=(upstream_model.max_table_size,), key=jax.random.PRNGKey((random.randint(0, 10))), dtype=jnp.float64),\n",
    "    'B': jnp.zeros(shape=(upstream_model.max_table_size,), dtype=jnp.float64)\n",
    "}\n",
    "opt = optax.adam(learning_rate=1e-2)\n",
    "opt_state = opt.init(mapping)\n",
    "\n",
    "X, X_test, Y, Y_test = train_test_split(X, Y, test_size=0.2)\n",
    "\n",
    "batch_size = 200\n",
    "\n",
    "best_loss = 1e10\n",
    "best_mapping = mapping\n",
    "for epoch in range(10):\n",
    "    total_loss = 0\n",
    "    X, Y = shuffle(X, Y)\n",
    "    for start in range(0, len(X), batch_size):\n",
    "        # print(start, mapping)\n",
    "        _X, _Y = X[start: start+batch_size], Y[start: start+batch_size]\n",
    "        \n",
    "        loss_value, gradient = jax.value_and_grad(final_mapping_cost_batch)(mapping, _X, _Y)\n",
    "        updates, opt_state = opt.update(gradient, opt_state, mapping)\n",
    "        mapping = optax.apply_updates(mapping, updates) \n",
    "        total_loss += loss_value    \n",
    "        \n",
    "    if epoch%10 ==0:\n",
    "        test_loss = final_mapping_cost(mapping, X_test, Y_test)\n",
    "        print('epoch  %i\\t| train loss = %.5f\\t|  test loss = %.5f' % (epoch, total_loss, test_loss))\n",
    "    \n",
    "        if test_loss < best_loss:\n",
    "            best_loss = test_loss\n",
    "            best_mapping = mapping\n",
    "            \n",
    "            \n",
    "model_path = 'mapping_1.pkl'\n",
    "with open(f'./temp_data/{model_path}', 'wb') as file:\n",
    "    pickle.dump(mapping, file)\n",
    "    \n",
    "with open(f'./temp_data/{model_path}', 'rb') as file:\n",
    "    mapping = pickle.load(file)       \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# neural_model = NeuralNetworkModel([4**n_qubits, 2**n_qubits, 2**n_qubits, n_qubits, upstream_model.max_table_size + 1])\n",
    "# neural_model.fit(Us, gate_vecs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "'int' object is not subscriptable",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn [26], line 18\u001b[0m\n\u001b[1;32m     16\u001b[0m gate_vec \u001b[39m=\u001b[39m jnp\u001b[39m.\u001b[39mwhere(gate_vec\u001b[39m>\u001b[39m(\u001b[39m1\u001b[39m\u001b[39m-\u001b[39m\u001b[39m1e-1\u001b[39m), \u001b[39m1\u001b[39m, \u001b[39m0\u001b[39m)\n\u001b[1;32m     17\u001b[0m \u001b[39m# TODO: \u001b[39;00m\n\u001b[0;32m---> 18\u001b[0m layer2gates \u001b[39m=\u001b[39m upstream_model\u001b[39m.\u001b[39;49mreconstruct(device, gate_vec)\n\u001b[1;32m     19\u001b[0m \u001b[39mprint\u001b[39m(layer2gates)\n\u001b[1;32m     20\u001b[0m params \u001b[39m=\u001b[39m  synthesis\u001b[39m.\u001b[39mSynthesisModel\u001b[39m.\u001b[39mfind_parmas(n_qubits, layer2gates, now_U)\n",
      "File \u001b[0;32m~/QuCT-Micro2023/upstream/randomwalk_model.py:461\u001b[0m, in \u001b[0;36mRandomwalkModel.reconstruct\u001b[0;34m(self, gate, gate_vector)\u001b[0m\n\u001b[1;32m    460\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mreconstruct\u001b[39m(\u001b[39mself\u001b[39m, gate, gate_vector: np\u001b[39m.\u001b[39marray) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mlist\u001b[39m:\n\u001b[0;32m--> 461\u001b[0m     paths \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mextract_paths_from_vec(gate, gate_vector)\n\u001b[1;32m    463\u001b[0m     \u001b[39m# TODO: 还要有一个判断是不是已经加进去了\u001b[39;00m\n\u001b[1;32m    464\u001b[0m     \u001b[39mdef\u001b[39;00m \u001b[39mparse_gate_info\u001b[39m(gate_info):\n",
      "File \u001b[0;32m~/QuCT-Micro2023/upstream/randomwalk_model.py:452\u001b[0m, in \u001b[0;36mRandomwalkModel.extract_paths_from_vec\u001b[0;34m(self, gate, gate_vector)\u001b[0m\n\u001b[1;32m    451\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mextract_paths_from_vec\u001b[39m(\u001b[39mself\u001b[39m, gate, gate_vector: np\u001b[39m.\u001b[39marray) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m \u001b[39mlist\u001b[39m:\n\u001b[0;32m--> 452\u001b[0m     device \u001b[39m=\u001b[39m extract_device(gate)\n\u001b[1;32m    453\u001b[0m     inclued_path_indexs \u001b[39m=\u001b[39m np\u001b[39m.\u001b[39margwhere(gate_vector\u001b[39m==\u001b[39m\u001b[39m1\u001b[39m)[:,\u001b[39m0\u001b[39m]\n\u001b[1;32m    454\u001b[0m     paths \u001b[39m=\u001b[39m [\n\u001b[1;32m    455\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdevice2reverse_path_table[device][index]\n\u001b[1;32m    456\u001b[0m         \u001b[39mfor\u001b[39;00m index \u001b[39min\u001b[39;00m inclued_path_indexs\n\u001b[1;32m    457\u001b[0m     ]\n",
      "File \u001b[0;32m~/QuCT-Micro2023/upstream/randomwalk_model.py:174\u001b[0m, in \u001b[0;36mextract_device\u001b[0;34m(gate)\u001b[0m\n\u001b[1;32m    173\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mextract_device\u001b[39m(gate):\n\u001b[0;32m--> 174\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mlen\u001b[39m(gate[\u001b[39m'\u001b[39;49m\u001b[39mqubits\u001b[39;49m\u001b[39m'\u001b[39;49m]) \u001b[39m==\u001b[39m \u001b[39m2\u001b[39m:\n\u001b[1;32m    175\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mtuple\u001b[39m(\u001b[39msorted\u001b[39m(gate[\u001b[39m'\u001b[39m\u001b[39mqubits\u001b[39m\u001b[39m'\u001b[39m]))\n\u001b[1;32m    176\u001b[0m     \u001b[39melse\u001b[39;00m:\n",
      "\u001b[0;31mTypeError\u001b[0m: 'int' object is not subscriptable"
     ]
    }
   ],
   "source": [
    "import importlib\n",
    "from downstream import synthesis\n",
    "importlib.reload(synthesis)\n",
    "target_U = unitary_group.rvs(2**n_qubits)\n",
    "\n",
    "now_U = jnp.array(target_U)\n",
    "I = jnp.eye(2**n_qubits)\n",
    "# if nowU is not identity\n",
    "now_dist = 1\n",
    "\n",
    "layer2gates_lists = []\n",
    "while now_dist > 1e-2:\n",
    "    vec = neural_model.predict([transformU(now_U)])[0]\n",
    "    device = round(float(vec[0]))\n",
    "    gate_vec = final_mapping(mapping, vec[1:])\n",
    "    gate_vec = jnp.where(gate_vec>(1-1e-1), 1, 0)\n",
    "    # TODO: \n",
    "    layer2gates = upstream_model.reconstruct(device, gate_vec)\n",
    "    # print(layer2gates)\n",
    "    params =  synthesis.SynthesisModel.find_parmas(n_qubits, layer2gates, now_U)\n",
    "    layer_U: jnp.array = layer_circuit_to_matrix(layer2gates, n_qubits, params)\n",
    "    \n",
    "    now_dist = now_U @ layer_U.T.conj()\n",
    "    \n",
    "    layer2gates_lists.append((params, layer2gates))\n",
    "    now_dist = matrix_distance_squared(now_U, target_U)\n",
    "    \n",
    "    print(now_dist)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[1.84419578, 0.46818063, 0.39372317, 0.43644778, 0.95936261,\n",
       "        0.14798604, 0.2792584 , 0.04758023, 0.08237355, 0.10970505,\n",
       "        0.01624282, 0.02887252]])"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "vec"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ISCA",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "a5cb17940ec456bfd6f6b24ecec011f7bb1827da42833da90014f36a02c01967"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
